---

- name: Update package index
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Remove unrequired dependencies
  apt:
    autoremove: yes

- name: Remove unrequired packages from cache
  apt:
    autoclean: yes
