global:
  scrape_interval:     1m
  scrape_timeout:      10s
  evaluation_interval: 1m

alerting:
  # alertmanagers:
  # - static_configs:
  #   - targets: ['localhost:9093']

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
